---
layout: post
toc: true
title: ML, Titanic Data
description: Exploring the Titanic dataset with machine learning. 
courses: { csp: {week: 25} }
type: ccc
---

In [2]:
# Uncomment the following lines to install the required packages
# !pip install seaborn
# !pip install pandas
# !pip install scikit-learn

In [3]:
import seaborn as sns

# Load the titanic dataset
exercise_data = sns.load_dataset('exercise')

print("Exercise Data")


print(exercise_data.columns) # titanic data set
display(exercise_data[['diet', 'pulse', 'time', 'kind']]) # look at selected columns

Exercise Data
Index(['Unnamed: 0', 'id', 'diet', 'pulse', 'time', 'kind'], dtype='object')

    id     diet  pulse    time     kind
0    1  low fat     85   1 min     rest
1    1  low fat     85  15 min     rest
2    1  low fat     88  30 min     rest
3    2  low fat     90   1 min     rest
4    2  low fat     92  15 min     rest
..  ..      ...    ...     ...      ...
85  29   no fat    135  15 min  running
86  29   no fat    130  30 min  running
87  30   no fat     99   1 min  running
88  30   no fat    111  15 min  running
89  30   no fat    150  30 min  running

[90 rows x 5 columns]

In [4]:

import seaborn as sns
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
print("Exercise Data")
print(exercise_data.columns)
display(exercise_data[['diet' ,'pulse' ,'time','kind']])
td = exercise_data.copy()  
# td.dropna(inplace=True) # no colomns with missing values in .csv (but uncomment if)
td['diet'] = td['diet'].astype('category').cat.codes
td['pulse'] = td['pulse'].astype('category').cat.codes 
td['time'] = td['time'].astype('category').cat.codes 
td['kind'] = td['kind'].astype('category').cat.codes 
print(td.columns)
display(td)

Exercise Data
Index(['Unnamed: 0', 'id', 'diet', 'pulse', 'time', 'kind'], dtype='object')

    id     diet  pulse    time     kind
0    1  low fat     85   1 min     rest
1    1  low fat     85  15 min     rest
2    1  low fat     88  30 min     rest
3    2  low fat     90   1 min     rest
4    2  low fat     92  15 min     rest
..  ..      ...    ...     ...      ...
85  29   no fat    135  15 min  running
86  29   no fat    130  30 min  running
87  30   no fat     99   1 min  running
88  30   no fat    111  15 min  running
89  30   no fat    150  30 min  running

[90 rows x 5 columns]

Index(['Unnamed: 0', 'id', 'diet', 'pulse', 'time', 'kind'], dtype='object')

    Unnamed: 0  id  diet  pulse  time  kind
0            0   0     1      4     0     0
1            1   0     1      4     1     0
2            2   0     1      7     2     0
3            3   1     1      9     0     0
4            4   1     1     11     1     0
..         ...  ..   ...    ...   ...   ...
85          85  28     0     35     1     2
86          86  28     0     33     2     2
87          87  29     0     18     0     2
88          88  29     0     27     1     2
89          89  29     0     38     2     2

[90 rows x 6 columns]

#### Median Values

In [11]:
print("id:")
median_id_cat_code= td['id'].median()
print(median_id_cat_code)
print("diet:")
median_diet_cat_code= td['diet'].median()
print(median_diet_cat_code)
print("pulse:")
median_pulse_cat_code= td['pulse'].median()
print(median_pulse_cat_code)
print("time:")
median_time_cat_code= td['time'].median()
print(median_time_cat_code)
print("kind:")
median_kind_cat_code= td['kind'].median()
print(median_kind_cat_code)

id:
14.5
diet:
0.5
pulse:
15.0
time:
1.0
kind:
1.0

#### Perished Mean/Average

In [12]:
# Calculate the median of the category codes for the 'kind' column
print("diet:")
mean_diet_cat_code= td['diet'].mean()
print(median_diet_cat_code)
print("pulse:")
mean_pulse_cat_code= td['pulse'].mean()
print(median_pulse_cat_code)
print("time:")
mean_time_cat_code= td['time'].mean()
print(median_time_cat_code)
print("kind:")
mean_kind_cat_code= td['kind'].mean()
print(median_kind_cat_code)

diet:
0.5
pulse:
15.0
time:
1.0
kind:
1.0

#### Survived Max and Min Stats

In [13]:
print("id:")
max_id_cat_code= td['id'].max()
print(max_id_cat_code)
min_pulse_cat_code= td['id'].min()
print(min_pulse_cat_code)

pulse:
38
0

In [8]:
import seaborn as sns
import pandas as pd
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
# Load the exercise dataset using Seaborn
exercise_data = sns.load_dataset('exercise')
# Display the columns and a sample of the dataset
print("Exercise Data Columns:")
print(exercise_data.columns)
print("\nSample of the Exercise Data:")
print(exercise_data[['id', 'diet', 'pulse', 'time', 'kind']].head())
# Split the data into features (X) and target (y)
X = exercise_data[['id', 'diet', 'time', 'kind']]
y = exercise_data['pulse']
# Perform one-hot encoding for the categorical columns
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), ['diet', 'time', 'kind'])], remainder='passthrough')
X_encoded = ct.fit_transform(X)
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_encoded, y, test_size=0.3, random_state=42)
# Train a linear regression model
regressor = LinearRegression()
regressor.fit(X_train, y_train)
# Print the model coefficients
print("Model Coefficients:")
print(regressor.coef_)
# Print the model intercept
print("Model Intercept:")
print(regressor.intercept_)
# Evaluate the model
y_pred = regressor.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error:", mse)

Exercise Data Columns:
Index(['Unnamed: 0', 'id', 'diet', 'pulse', 'time', 'kind'], dtype='object')

Sample of the Exercise Data:
   id     diet  pulse    time  kind
0   1  low fat     85   1 min  rest
1   1  low fat     85  15 min  rest
2   1  low fat     88  30 min  rest
3   2  low fat     90   1 min  rest
4   2  low fat     92  15 min  rest
Model Coefficients:
[  2.06438483  -2.06438483  -6.79921446   1.24599372   5.55322074
  16.66418351 -11.13404753  -5.53013598   2.47242722]
Model Intercept:
61.022865444661036
Mean Squared Error: 78.1710950281351

In [15]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
# Load the exercise dataset
exercise_data = pd.read_csv("../exercise.csv")
# Define a new passenger
passenger = pd.DataFrame({
    'id': [1],  # Choose an ID that does not exist in the original dataset
    'diet': ['low fat'],
    'time': ['1 min'],
    'kind': ['rest']
})
# Preprocess the new passenger data
new_passenger = pd.get_dummies(passenger, columns=['diet', 'time', 'kind'])
# Combine the new passenger's data with the original dataset
combined_data = pd.concat([exercise_data, new_passenger], ignore_index=True)
# Split the data into features (X) and target (y)
X = combined_data[['id', 'diet', 'time', 'kind']]
y = combined_data['pulse']
# Perform one-hot encoding for the categorical columns
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), ['diet', 'time', 'kind'])], remainder='passthrough')
X_encoded = ct.fit_transform(X)
# Train a linear regression model
regressor = LinearRegression()
regressor.fit(X_encoded[:-1], y[:-1])  # Exclude the last row which is the new passenger's data
# Predict the pulse rate for the new passenger
pulse_prediction = regressor.predict(X_encoded[-1:])  # Predict for the last row which is the new passenger's data
# Round off the predicted pulse rate to two decimal places
rounded_pulse_prediction = round(pulse_prediction[0], 2)
# Print the predicted pulse rate
print('Predicted Pulse Rate:', rounded_pulse_prediction)

Predicted Pulse Rate: 75.29